/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 8
#define ALIAS_COUNT 2
#define TOKEN_COUNT 3
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__separator = 1,
  sym__chunk = 2,
  sym_template = 3,
  sym_separator = 4,
  sym_ini_section = 5,
  sym_php_section = 6,
  sym_twig_section = 7,
  alias_sym_php_content = 8,
  alias_sym_twig_content = 9,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__separator] = "_separator",
  [sym__chunk] = "ini_content",
  [sym_template] = "template",
  [sym_separator] = "separator",
  [sym_ini_section] = "ini_section",
  [sym_php_section] = "php_section",
  [sym_twig_section] = "twig_section",
  [alias_sym_php_content] = "php_content",
  [alias_sym_twig_content] = "twig_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__separator] = sym__separator,
  [sym__chunk] = sym__chunk,
  [sym_template] = sym_template,
  [sym_separator] = sym_separator,
  [sym_ini_section] = sym_ini_section,
  [sym_php_section] = sym_php_section,
  [sym_twig_section] = sym_twig_section,
  [alias_sym_php_content] = alias_sym_php_content,
  [alias_sym_twig_content] = alias_sym_twig_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [sym__chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_ini_section] = {
    .visible = true,
    .named = true,
  },
  [sym_php_section] = {
    .visible = true,
    .named = true,
  },
  [sym_twig_section] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_php_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_twig_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_twig_content,
  },
  [2] = {
    [0] = alias_sym_php_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 4,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      if (eof) ADVANCE(1);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__separator] = ACTIONS(1),
    [sym__chunk] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(15),
    [sym_separator] = STATE(2),
    [sym_ini_section] = STATE(10),
    [sym_twig_section] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__separator] = ACTIONS(5),
    [sym__chunk] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_separator] = STATE(5),
    [sym_php_section] = STATE(11),
    [sym_twig_section] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym__separator] = ACTIONS(11),
    [sym__chunk] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_separator] = STATE(6),
    [sym_php_section] = STATE(12),
    [sym_twig_section] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym__separator] = ACTIONS(11),
    [sym__chunk] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(17), 3,
      sym__separator,
      sym__chunk,
      ts_builtin_sym_end,
  [6] = 3,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym__chunk,
    STATE(20), 1,
      sym_twig_section,
  [16] = 3,
    ACTIONS(21), 1,
      sym__chunk,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_twig_section,
  [26] = 3,
    ACTIONS(21), 1,
      sym__chunk,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      sym_twig_section,
  [36] = 2,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym__separator,
  [43] = 2,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym__separator,
  [50] = 2,
    ACTIONS(5), 1,
      sym__separator,
    STATE(3), 1,
      sym_separator,
  [57] = 2,
    ACTIONS(11), 1,
      sym__separator,
    STATE(6), 1,
      sym_separator,
  [64] = 2,
    ACTIONS(11), 1,
      sym__separator,
    STATE(7), 1,
      sym_separator,
  [71] = 1,
    ACTIONS(17), 2,
      sym__chunk,
      ts_builtin_sym_end,
  [76] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [80] = 1,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
  [84] = 1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
  [88] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [92] = 1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
  [96] = 1,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [100] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [104] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 6,
  [SMALL_STATE(6)] = 16,
  [SMALL_STATE(7)] = 26,
  [SMALL_STATE(8)] = 36,
  [SMALL_STATE(9)] = 43,
  [SMALL_STATE(10)] = 50,
  [SMALL_STATE(11)] = 57,
  [SMALL_STATE(12)] = 64,
  [SMALL_STATE(13)] = 71,
  [SMALL_STATE(14)] = 76,
  [SMALL_STATE(15)] = 80,
  [SMALL_STATE(16)] = 84,
  [SMALL_STATE(17)] = 88,
  [SMALL_STATE(18)] = 92,
  [SMALL_STATE(19)] = 96,
  [SMALL_STATE(20)] = 100,
  [SMALL_STATE(21)] = 104,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 1, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 2, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 2, 2, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_separator, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 2, 3, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 3, 3, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 4, 3, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_twig_section, 1, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ini_section, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_php_section, 1, 0, 2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 1, 0),
  [35] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 3, 2, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 5, 3, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__separator = 0,
  ts_external_token__chunk = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__separator] = sym__separator,
  [ts_external_token__chunk] = sym__chunk,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__separator] = true,
    [ts_external_token__chunk] = true,
  },
  [2] = {
    [ts_external_token__chunk] = true,
  },
  [3] = {
    [ts_external_token__separator] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_october_external_scanner_create(void);
void tree_sitter_october_external_scanner_destroy(void *);
bool tree_sitter_october_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_october_external_scanner_serialize(void *, char *);
void tree_sitter_october_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_october(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_october_external_scanner_create,
      tree_sitter_october_external_scanner_destroy,
      tree_sitter_october_external_scanner_scan,
      tree_sitter_october_external_scanner_serialize,
      tree_sitter_october_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
